# $schema: https://json.schemastore.org/github-workflow.json
name: check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: check-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - uses: reviewdog/action-setup@v1
      - name: run android lint
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          ./gradlew lintDebug -PabortOnError
      - name: run detekt
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          ./gradlew detekt
      - name: run reviewdog review
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat tenugui/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="tenugui android lint" -reporter=github-pr-review;
          cat tests/build/reports/lint-results-debug.sarif | reviewdog -f=sarif -name="tests android lint" -reporter=github-pr-review;
          cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-review;
      - name: run reviewdog suggest
        if: ${{ !cancelled() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew lintFix detekt -PautoCorrect -PabortOnError --quiet --continue;
          TMPFILE=$(mktemp);
          git diff >"${TMPFILE}";
          git stash -u || git stash drop;
          cat "${TMPFILE}" | reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review;

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: check api file
        shell: bash
        run: |
          ./gradlew apiCheck

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: publish
        shell: bash
        run: |
          ./gradlew publishAllPublicationsToLocalRepository --no-configuration-cache

  androidTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: run android test
        uses: ./.github/actions/avd
        with:
          prepare-script: ./gradlew :tests:assembleDebug :tests:assembleDebugAndroidTest
          script: ./gradlew :tests:connectedDebugAndroidTest
      - uses: actions/upload-artifact@v5
        if: ${{ failure() }}
        with:
          name: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: tests/build/outputs/androidTest-results/connected/debug/*.png
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: android-test-result
          path: '**/outputs/androidTest-results/connected/**/*.xml'
          reporter: java-junit
          fail-on-error: false

  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/java
      - uses: ./.github/actions/gradle
      - name: run unit test
        shell: bash
        run: |
          ./gradlew testDebugUnitTest
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: unit-test-result
          path: '**/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
